GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios HTTP/1.1
content-type: application/json

{
    "nome": "Eduardo",
    "sobrenome": "Dias",
    "email": "eduardo@gmail.com",
    "senha": "123",
    "permissao": "aluno",
    "status": "Ativo",
    "dataCadastro": "2022-12-04T05:37:00.915Z",
    "dataAcesso": "20220915",
    "dataAtualizacao": "20220919"
}

###
PUT http://localhost:3000/usuarios HTTP/1.1
content-type: application/json

{
    "id_user": " ",
    "name": "Eduardo",
    "sobrenome": "Ferreira",
    "email": "eduardo@gmail.com",
    "password": "senha123"
}

###
DELETE  http://localhost:3000/usuarios HTTP/1.1
content-type: application/json

{
    "_id":"6328f90ffc9aa4cb74eac97b"
}